-- 风控规则表：一行 = 一段 GRL 文本（对应一个 .grl 文件，可含多条 rule）。
-- 服务按 ENABLED=1 全量加载，ORDER BY RULE_NAME 保证内容指纹稳定；
-- 修改 GRL_CONTENT / ENABLED 后无需重启服务，下个轮询周期自动热加载。

CREATE TABLE RISK_RULES (
    ID          NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    RULE_NAME   VARCHAR2(100)  NOT NULL,
    GRL_CONTENT CLOB           NOT NULL,
    ENABLED     NUMBER(1)      DEFAULT 1 NOT NULL,
    DESCRIPTION VARCHAR2(500),
    UPDATED_AT  TIMESTAMP      DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT UK_RISK_RULES_NAME UNIQUE (RULE_NAME),
    CONSTRAINT CK_RISK_RULES_ENABLED CHECK (ENABLED IN (0, 1))
);

COMMENT ON TABLE  RISK_RULES             IS '风控规则表：存储 grule GRL 规则文本';
COMMENT ON COLUMN RISK_RULES.RULE_NAME   IS '规则资源名（对应 .grl 文件名），唯一';
COMMENT ON COLUMN RISK_RULES.GRL_CONTENT IS 'GRL 规则文本，可包含多条 rule';
COMMENT ON COLUMN RISK_RULES.ENABLED     IS '1 启用 0 停用；停用即从下个轮询周期起下线';
COMMENT ON COLUMN RISK_RULES.UPDATED_AT  IS '最后更新时间（ruleloader/人工更新时刷新）';

-- 示例数据（完整规则集用 cmd/ruleloader 从 rules/ 目录批量导入）：
--   go run ./cmd/ruleloader -dsn 'oracle://user:pass@host:1521/svc' -dir rules
INSERT INTO RISK_RULES (RULE_NAME, GRL_CONTENT, DESCRIPTION) VALUES (
    '000_example.grl',
    'rule ExampleApprove "示例：默认放行" salience 1 {
    when
        Result.Decision == ""
    then
        Result.Decision = "approve";
        Result.AddHit("ExampleApprove");
}',
    '示例规则：验证链路用，导入完整规则集后可停用'
);

COMMIT;
